import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { CircuitBoard, FileText, ShieldCheck, AlertCircle, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";

type PublicBoard = { designation: string; serialNumber: string | null; manufacturer: string; productionDate: string | null; documentationStatus: string; contact: { name: string; address?: string | null; phone?: string | null; email?: string | null }; publicDocuments: Array<{ sha256: string; documentType: string; version: number; originalFileName: string; uploadedAt: string }>; internal?: Record<string, string | null> };
export default function SwitchboardPublic() {
  const [path] = useLocation(); const token = path.split("/q/board/")[1]?.split(/[/?#]/)[0] ?? "";
  const [data, setData] = useState<PublicBoard | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); void fetch(`/api/q/board/${encodeURIComponent(token)}`, { signal: controller.signal, cache: "no-store" }).then(async (response) => { const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "QR odkaz se nepodařilo načíst."); setData(body); }).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "QR odkaz se nepodařilo načíst."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [token]);
  return <main className="min-h-[100dvh] bg-neutral-100 text-neutral-900"><header className="bg-white border-b px-4 py-3"><div className="max-w-xl mx-auto flex items-center gap-2"><CircuitBoard className="h-6 w-6 text-cyan-700" /><span className="font-bold">Dokumentace rozvaděče</span></div></header><div className="max-w-xl mx-auto p-4 space-y-4">{loading && <div className="py-20 text-center text-sm text-neutral-500">Načítám dokumentaci…</div>}{error && <div className="border border-red-200 bg-red-50 p-6 text-center"><AlertCircle className="h-10 w-10 mx-auto text-red-600 mb-2" /><div className="font-semibold">Odkaz není dostupný</div><p className="text-sm text-neutral-600 mt-1">{error}</p></div>}{data && <><section className="bg-white border p-5"><div className="flex items-start gap-3"><ShieldCheck className="h-7 w-7 text-emerald-600" /><div><h1 className="text-2xl font-bold">{data.designation}</h1><p className="text-sm text-neutral-500">{data.manufacturer}</p></div></div><dl className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm mt-5"><dt className="text-neutral-500">Výrobní číslo</dt><dd className="font-medium">{data.serialNumber || "—"}</dd><dt className="text-neutral-500">Datum výroby</dt><dd>{data.productionDate || "—"}</dd><dt className="text-neutral-500">Dokumentace</dt><dd>{data.documentationStatus === "completed" ? "Zkontrolována" : "Ve zpracování"}</dd></dl></section>{data.publicDocuments.length > 0 && <section className="bg-white border"><div className="px-4 py-3 border-b font-semibold flex items-center gap-2"><FileText className="h-4 w-4" />Veřejné dokumenty</div><div className="divide-y">{data.publicDocuments.map((document) => <a key={`${document.sha256}-${document.version}`} href={`/api/q/board/${token}/documents/${document.sha256}`} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-4 hover:bg-neutral-50"><FileText className="h-5 w-5 text-neutral-500" /><div className="flex-1 min-w-0"><div className="font-medium truncate">{document.originalFileName}</div><div className="text-xs text-neutral-500">Verze {document.version}</div></div><ExternalLink className="h-4 w-4" /></a>)}</div></section>}<section className="bg-white border p-4 text-sm"><div className="font-semibold">Kontakt</div><div className="mt-1 text-neutral-600">{data.contact.name}</div>{data.contact.address && <div>{data.contact.address}</div>}{data.contact.phone && <div>{data.contact.phone}</div>}{data.contact.email && <Button variant="outline" size="sm" className="mt-3" asChild><a href={`mailto:${data.contact.email}`}>Napsat e-mail</a></Button>}</section></>}</div></main>;
}
