import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, GitCompareArrows, RefreshCw, Save, ScanText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAuth } from "@/hooks/use-auth";
import { useToast } from "@/hooks/use-toast";
import { switchboardFetch, type SwitchboardDocumentComparison, type SwitchboardExtractionDocument, type SwitchboardExtractedField } from "@/lib/switchboards-api";

const LABELS: Record<string, string> = { boardDesignation: "Označení rozvaděče", serialNumber: "Výrobní číslo", productionDate: "Datum výroby", typeDesignation: "Typ", networkSystem: "Soustava", ratedVoltage: "Napětí", ratedFrequency: "Frekvence", ratedCurrent: "Jmenovitý proud", standard: "Normy", dimensions: "Rozměry", ipRating: "IP", ikRating: "IK", weight: "Hmotnost" };

export function SwitchboardExtractionReview({ switchboardId }: { switchboardId: number }) {
  const { can } = useAuth(); const { toast } = useToast(); const qc = useQueryClient();
  const key = ["switchboard-extractions", switchboardId];
  const { data = [], isLoading } = useQuery({ queryKey: key, queryFn: () => switchboardFetch<SwitchboardExtractionDocument[]>(`/api/switchboards/${switchboardId}/extractions`), enabled: can("switchboards.extraction.review") });
  const [selectedId, setSelectedId] = useState<string>(""); const [compareFromId, setCompareFromId] = useState(""); const [compareToId, setCompareToId] = useState(""); const [editing, setEditing] = useState<SwitchboardExtractedField | null>(null); const [value, setValue] = useState(""); const [reason, setReason] = useState("");
  const [adding, setAdding] = useState<{ fieldKey: string; canonicalNameCs: string } | null>(null);
  useEffect(() => { if (!selectedId && data[0]) setSelectedId(String(data[0].id)); }, [data, selectedId]);
  useEffect(() => { if (data.length < 2) return; if (!data.some((doc) => String(doc.id) === compareFromId)) setCompareFromId(String(data[1].id)); if (!data.some((doc) => String(doc.id) === compareToId)) setCompareToId(String(data[0].id)); }, [data, compareFromId, compareToId]);
  const selected = data.find((doc) => String(doc.id) === selectedId) ?? data[0];
  const canCompare = !!compareFromId && !!compareToId && compareFromId !== compareToId;
  const compareUrl = canCompare ? `/api/switchboards/${switchboardId}/documents/compare?from=${compareFromId}&to=${compareToId}` : null;
  const { data: comparison, isLoading: comparisonLoading } = useQuery({ queryKey: ["switchboard-comparison", switchboardId, compareFromId, compareToId], queryFn: () => switchboardFetch<SwitchboardDocumentComparison>(compareUrl!), enabled: !!compareUrl });
  const correction = useMutation({ mutationFn: () => switchboardFetch(`/api/switchboards/${switchboardId}/extractions/${editing!.id}`, { method: "PATCH", body: JSON.stringify({ value, reason }) }), onSuccess: () => { void qc.invalidateQueries({ queryKey: key }); void qc.invalidateQueries({ queryKey: ["switchboards", switchboardId] }); setEditing(null); toast({ title: "Oprava byla uložena do auditu" }); }, onError: (error) => toast({ variant: "destructive", title: "Oprava selhala", description: error.message }) });
  const addMissing = useMutation({ mutationFn: () => switchboardFetch(`/api/switchboards/${switchboardId}/extractions`, { method: "POST", body: JSON.stringify({ documentId: selected!.id, fieldKey: adding!.fieldKey, value, reason }) }), onSuccess: () => { void qc.invalidateQueries({ queryKey: key }); void qc.invalidateQueries({ queryKey: ["switchboards", switchboardId] }); setAdding(null); toast({ title: "Chybějící pole bylo ručně potvrzeno" }); }, onError: (error) => toast({ variant: "destructive", title: "Doplnění selhalo", description: error.message }) });
  const reprocess = useMutation({ mutationFn: () => switchboardFetch(`/api/switchboards/${switchboardId}/documents/${selected!.id}/reprocess`, { method: "POST" }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["switchboard-documents", switchboardId] }); toast({ title: "Dokument byl znovu zařazen do zpracování" }); }, onError: (error) => toast({ variant: "destructive", title: "Nelze spustit zpracování", description: error.message }) });
  const sorted = useMemo(() => [...(selected?.fields ?? [])].sort((a, b) => (LABELS[a.fieldKey] ?? a.fieldKey).localeCompare(LABELS[b.fieldKey] ?? b.fieldKey, "cs")), [selected]);
  if (!can("switchboards.extraction.review")) return null;
  return <section className="mt-5 border-y bg-card"><div className="p-4 border-b flex items-center gap-3"><ScanText className="h-5 w-5 text-cyan-600" /><div className="flex-1"><h2 className="font-semibold">Kontrola vytěžených údajů</h2><p className="text-xs text-muted-foreground">Původní hodnoty zůstávají zachované</p></div>{selected && <Button size="sm" variant="outline" disabled={reprocess.isPending} onClick={() => reprocess.mutate()}><RefreshCw className={`h-4 w-4 mr-1 ${reprocess.isPending ? "animate-spin" : ""}`} />Znovu zpracovat</Button>}</div>
    {isLoading ? <div className="p-4 text-sm text-muted-foreground">Načítám vytěžená pole…</div> : !selected ? <div className="p-4 text-sm text-muted-foreground">Nejprve nahrajte SchrackNorm DBO PDF.</div> : <><div className="p-4 border-b"><Label className="text-xs">Kontrolovaná verze</Label><Select value={String(selected.id)} onValueChange={setSelectedId}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{data.map((doc) => <SelectItem key={doc.id} value={String(doc.id)}>DBO verze {doc.version} · {doc.originalFileName}</SelectItem>)}</SelectContent></Select></div>
      {data.length >= 2 && <div className="p-4 border-b bg-muted/20"><div className="font-medium text-sm mb-2 flex items-center gap-2"><GitCompareArrows className="h-4 w-4" />Porovnání verzí DBO</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><Select value={compareFromId} onValueChange={setCompareFromId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{data.map((doc) => <SelectItem key={doc.id} value={String(doc.id)}>Původní: verze {doc.version}</SelectItem>)}</SelectContent></Select><Select value={compareToId} onValueChange={setCompareToId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{data.map((doc) => <SelectItem key={doc.id} value={String(doc.id)}>Nová: verze {doc.version}</SelectItem>)}</SelectContent></Select></div>{compareFromId === compareToId && <p className="text-xs text-destructive mt-2">Vyberte dvě rozdílné verze.</p>}{comparisonLoading && <p className="text-xs text-muted-foreground mt-2">Porovnávám…</p>}{comparison && <div className="mt-3"><div className="text-xs text-muted-foreground mb-2">DBO v{comparison.from.version} → v{comparison.to.version} · nalezeno změn: {comparison.changes.length}</div>{comparison.changes.length ? <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b"><th className="text-left py-2">Pole</th><th className="text-left py-2">Původní hodnota</th><th className="text-left py-2">Nová hodnota</th></tr></thead><tbody>{comparison.changes.map((change) => <tr key={change.fieldKey} className="border-b last:border-0"><td className="py-2 pr-3 font-medium">{change.canonicalNameCs}</td><td className="py-2 pr-3 text-red-700">{change.before?.effectiveValue ?? "Nenalezeno"}</td><td className="py-2 text-emerald-700">{change.after?.effectiveValue ?? "Nenalezeno"}</td></tr>)}</tbody></table></div> : <p className="text-xs text-emerald-700">Vytěžené hodnoty se neliší.</p>}</div>}</div>}
      {selected.missingFields.length > 0 && <div className="p-4 border-b bg-amber-50 dark:bg-amber-950/20"><div className="font-medium text-sm mb-2">Chybějící povinná pole</div><div className="flex flex-wrap gap-2">{selected.missingFields.map((field) => <Button key={field.fieldKey} size="sm" variant="outline" disabled={!can("switchboards.extraction.correct")} onClick={() => { setAdding(field); setValue(""); setReason(""); }}>{field.canonicalNameCs}</Button>)}</div></div>}
      <div className="divide-y">{sorted.map((field) => { const ok = field.validationStatus === "valid" && (field.confidence >= 0.85 || field.manuallyCorrected); return <div key={field.id} className="p-4 flex gap-3 items-start"><div className="mt-0.5">{ok ? <CheckCircle2 className="h-5 w-5 text-emerald-600" /> : <AlertTriangle className="h-5 w-5 text-amber-600" />}</div><div className="flex-1 min-w-0"><div className="font-medium text-sm">{LABELS[field.fieldKey] ?? field.fieldKey}</div><div className="text-sm mt-1 break-words">{field.effectiveValue ?? "Hodnota nenalezena"}</div><div className="text-xs text-muted-foreground mt-1">Název: {field.foundLabel}{field.matchedAlias ? ` · alias ${field.matchedAlias}` : ""} · strana {field.pageNumber} · jistota {Math.round(field.confidence * 100)} % · {field.extractionMethod === "ocr" ? "OCR" : "textová vrstva"}</div>{field.manuallyCorrected && <div className="text-xs text-blue-600 mt-1">Ručně opraveno · původně: {field.rawValue ?? "—"}</div>}{field.validationMessage && <div className="text-xs text-destructive mt-1">{field.validationMessage}</div>}</div>{can("switchboards.extraction.correct") && <Button size="sm" variant="outline" onClick={() => { setEditing(field); setValue(field.effectiveValue ?? ""); setReason(""); }}>Opravit</Button>}</div>; })}</div></>}
    <Dialog open={!!editing} onOpenChange={(open) => !open && setEditing(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Opravit {editing ? LABELS[editing.fieldKey] ?? editing.fieldKey : "pole"}</DialogTitle></DialogHeader><div className="space-y-4"><div className="text-xs text-muted-foreground">Raw hodnota: {editing?.rawValue ?? "nenalezena"}</div><div className="space-y-1.5"><Label htmlFor="correction-value">Potvrzená hodnota</Label><Input id="correction-value" value={value} onChange={(e) => setValue(e.target.value)} /></div><div className="space-y-1.5"><Label htmlFor="correction-reason">Důvod opravy</Label><Textarea id="correction-reason" value={reason} onChange={(e) => setReason(e.target.value)} rows={3} /></div><Button className="w-full" disabled={!value.trim() || reason.trim().length < 3 || correction.isPending} onClick={() => correction.mutate()}><Save className="h-4 w-4 mr-2" />Uložit opravu</Button></div></DialogContent></Dialog>
    <Dialog open={!!adding} onOpenChange={(open) => !open && setAdding(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Doplnit {adding?.canonicalNameCs}</DialogTitle></DialogHeader><div className="space-y-4"><p className="text-xs text-muted-foreground">Pole nebylo v PDF pojmenované nebo nalezené. Zadejte pouze ověřenou hodnotu z evidence.</p><div className="space-y-1.5"><Label htmlFor="missing-value">Potvrzená hodnota</Label><Input id="missing-value" value={value} onChange={(e) => setValue(e.target.value)} /></div><div className="space-y-1.5"><Label htmlFor="missing-reason">Zdroj a důvod doplnění</Label><Textarea id="missing-reason" value={reason} onChange={(e) => setReason(e.target.value)} rows={3} /></div><Button className="w-full" disabled={!value.trim() || reason.trim().length < 3 || addMissing.isPending} onClick={() => addMissing.mutate()}><Save className="h-4 w-4 mr-2" />Uložit potvrzenou hodnotu</Button></div></DialogContent></Dialog>
  </section>;
}
