import { Router, type IRouter } from "express";
import healthRouter from "./health";
import jobsRouter from "./jobs";
import tasksRouter from "./tasks";
import attachmentsRouter from "./attachments";
import materialsRouter from "./materials";
import peopleRouter from "./people";
import customersRouter from "./customers";
import customerContactsRouter from "./customer-contacts";
import customerSitesRouter from "./customer-sites";
import customerSiteAttachmentsRouter from "./customer-site-attachments";
import customerDocumentsRouter from "./customer-documents";
import deviceCredentialsRouter from "./device-credentials";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import authRouter from "./auth";
import securityQuestionsRouter from "./security-questions";
import usersRouter from "./users";
import preferencesRouter from "./preferences";
import activitiesRouter from "./activities";
import visitsRouter from "./visits";
import activityVisitsRouter from "./activity-visits";
import meRouter from "./me";
import machinesRouter from "./machines";
import warehouseItemsRouter from "./warehouse-items";
import auditRouter from "./audit";
import gdprRouter from "./gdpr";
import timeEntriesRouter from "./time-entries";
import statsRouter from "./stats";
import emailSettingsRouter from "./email-settings";
import emailImportSettingsRouter from "./email-import-settings";
import backupsRouter from "./backups";
import billingRouter from "./billing";
import billingDocumentsRouter from "./billing-documents";
import emailImportRouter from "./email-import";
import eventsRouter from "./events";
import risksRouter from "./risks";
import clientErrorsRouter from "./client-errors";
import leavesRouter from "./leaves";
import publicHolidaysRouter from "./public-holidays";
import ppeRouter from "./ppe";
import sessionsRouter from "./sessions";
import signRouter from "./sign";
import quotesRouter from "./quotes";
import webauthnRouter from "./webauthn";

const router: IRouter = Router();

router.use(healthRouter);
router.use(jobsRouter);
router.use(tasksRouter);
router.use(attachmentsRouter);
router.use(materialsRouter);
router.use(peopleRouter);
router.use(customersRouter);
router.use(customerContactsRouter);
router.use(customerSitesRouter);
router.use(customerSiteAttachmentsRouter);
router.use(customerDocumentsRouter);
router.use(deviceCredentialsRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(securityQuestionsRouter);
router.use(usersRouter);
router.use(preferencesRouter);
router.use(activitiesRouter);
router.use(visitsRouter);
router.use(activityVisitsRouter);
router.use(meRouter);
router.use(machinesRouter);
router.use(warehouseItemsRouter);
router.use(auditRouter);
router.use(gdprRouter);
router.use(timeEntriesRouter);
router.use(statsRouter);
router.use(emailSettingsRouter);
router.use(emailImportSettingsRouter);
router.use(backupsRouter);
router.use(billingRouter);
router.use(billingDocumentsRouter);
router.use(emailImportRouter);
router.use(eventsRouter);
router.use(risksRouter);
router.use(clientErrorsRouter);
router.use(leavesRouter);
router.use(publicHolidaysRouter);
router.use(ppeRouter);
router.use(sessionsRouter);
router.use(signRouter);
router.use(quotesRouter);
router.use(webauthnRouter);

export default router;
